fixed error "ImportError: cannot import name 'cached_download' from 'huggingface_hub" for sentence-transformers==2.2.2 is required huggingface_hub==0.25.2